# Generated by Django 2.2 on 2020-01-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_belt', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='app_for_belt.User'),
            preserve_default=False,
        ),
    ]
